name: 'Palm Log analysis'
description: 'Provide summary and possible fixes for generated log files'

inputs:
  file_path:
    description: 'Path to log file'
    required: true
  api-key:
    description: 'PALM api key'
    required: true
  output-file:
    description: 'Name for the artifact generated'
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: ls
      shell: bash
    - run: entrypoint.sh 
      shell: bash
    - run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: python ${{ github.action_path }}/main.py ${{ inputs.file_path }} ${{ inputs.api-key }} >> result.txt
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output-file }}
        path: ./result.txt
